### ISSUE TITLE
need bin directory

### ISSUE THREAD

**Issue by sjtpharm** [metrumresearchgroup/expo1-nonmem-foce#2]
Instructions to install bbi [on this page (section 5.2) ](https://merge.metrumrg.com/zy8x3BETA7R5Ph/posts/about-the-repo.html) fail because there is no bin directory.  Suggest to modify instructions or add a bin directory to the repo so it's there when we download.  Thanks! Stacey

**Comment by seth127** [comment]
Thanks, good catch @sjtpharm! That `bin` directory should be there, but seems to have gotten lost in the shuffle. We'll make sure to add it so that the instructions work as written.

**Comment by seth127** [comment]
Fixed in a3a51e1
