### ISSUE TITLE
Silence or address mrgsolve warnings

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/expo1-nonmem-foce#8]
Silence or address mrgsolve warnings [here](https://merge.metrumrg.com/expo/expo1-nonmem-foce/posts/pk-vpc-final.html#simulate-for-vpc)

![image](https://github.com/metrumresearchgroup/expo1-nonmem-foce/assets/18685116/1c7999a2-af9f-4eb8-b522-ed7685015572)

**Comment by kylebaron** [comment]
Hi @barrettk  - I think we just shouldn't pass `quiet`; it isn't an argument. I probably put it in by mistake and then refactored at a later date to surface this warning.

**Comment by barrettk** [comment]
Thanks @kylebaron. Closing this issue, but added your details to the new one I made in our private repo
